export const SESSION_INACTIVITY_MINUTES = 30;

export const SESSION_INACTIVITY_MS = SESSION_INACTIVITY_MINUTES * 60 * 1000;

export const SESSION_INACTIVITY_SECONDS = SESSION_INACTIVITY_MINUTES * 60;

export const SESSION_REFRESH_INTERVAL_MS = 5 * 60 * 1000;

export const SESSION_IDLE_CHECK_INTERVAL_MS = 30 * 1000;
